matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  yarn: true

install:
  - yarn install

script:
  - yarn run build
  - yarn run pack
  - zip --junk-paths mac-falcon-v$(node -p "require('./package.json').version").zip release/*.dmg

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

addons:
  artifacts:
    s3_region: us-east-1
    paths: $(ls mac-falcon-v*.zip | tr "\n" ":")
    debug: true
