version: 0.4.{build}

environment:
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

platform:
  - x64
  - x86

services:
  - postgresql96

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%


install:
  - ps: Install-Product node 7 x64
  - yarn install

build_script:
  - npm run build
  - npm run package

after_build:
  - 7z a release.zip release

artifacts:
  - path: release.zip
    name: release

test: off
