version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
      - image: quay.io/plotly/falcon-test-spark
      - image: quay.io/plotly/falcon-test-db2
    environment:
      PATH: "/usr/local/opt/curl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/circleci/project/node_modules/.bin"
    working_directory: /home/circleci/falcon
    steps:
      - restore_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          keys:
            - v1-source-{{ .Branch }}-
            - v1-source-
      - checkout
      - save_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          key: v2-yarn-{{ checksum "yarn.lock" }}
          keys:
            - v2-yarn-
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn run rebuild:modules:electron
      - save_cache:
          key: v2-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run build
      - run: yarn run test
      - run: yarn run pack
      
      # create artifacts/ and move installer from release/falcon-sql-client-vM.m.p.tar.gz to artifacts/linux-falcon-vM.m.p.tar.gz
      - run: mkdir artifacts
      - run: for f in release/falcon-sql-client-*.tar.gz ; do mv $f artifacts/linux-falcon-v${f#release/falcon-sql-client-}; done
      
      - store_artifacts:
          path: artifacts
